src/Entity/User.php
<?php
/**
 * Created by PhpStorm.
 * User: syfea
 * Date: 11/03/19
 * Time: 09:45
 */

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $website;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="text")
     */
    private $contact;

    /**
     * @ORM\Column(type="text")
     */
    private $about_me;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $linkedin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $git;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getAboutMe(): ?string
    {
        return $this->about_me;
    }

    public function setAboutMe(string $about_me): self
    {
        $this->about_me = $about_me;

        return $this;
    }

    public function getContact(): ?string
    {
        return $this->contact;
    }

    public function setContact(string $contact): self
    {
        $this->contact = $contact;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(?string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }

    public function getGit(): ?string
    {
        return $this->git;
    }

    public function setGit(?string $git): self
    {
        $this->git = $git;

        return $this;
    }
}

templates/front/about.html.twig
<div id="fh5co-about" class="animate-box">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>A propos de moi</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <ul class="info">
                    <li><span class="first-block">Nom :</span><span class="second-block">{{ user.name }}</span></li>
                    <li><span class="first-block">Phone :</span><span class="second-block">{{ user.phone }}</span></li>
                    <li><span class="first-block">Email :</span><span class="second-block">{{ user.email }}</span></li>
                    <li><span class="first-block">Website :</span><span class="second-block">{{ user.website }}</span></li>
                    <li><span class="first-block">Address :</span><span class="second-block">{{ user.address }}</span></li>
                </ul>
            </div>
            <div class="col-md-8">
                <p>{{ user.aboutMe|nl2br  }}</p>
                <ul class="fh5co-social-icons">
                    <li><a href="https://github.com/syfea"><i class="icon-github"></i></a></li>
                    <li><a href="https://www.linkedin.com/in/sylvain-feasson/"><i class="icon-linkedin2"></i></a></li>
                </ul>
                </p>
            </div>
        </div>
    </div>
</div>

templates/front/blog.html.twig
<div id="fh5co-blog">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>{{ category.title }}</h2>
                <p>{{ category.description }}</p>
            </div>
        </div>
        <div class="row">
            {% for article in category.articles %}
            <div class="col-md-4">
                <div class="fh5co-blog animate-box">
                    <a href="{{ path('index_article', {id: article.id}) }}" class="blog-bg" style="background-image: url({{ api.getImageUrl(article.image) }});"></a>
                    <div class="blog-text">
                        <h3><a href="{{ path('index_article', {id: article.id}) }}">{{ article.title }}</a></h3>
                        <p>{{ article.content|slice(0, 120)|raw }}</p>
                        <ul class="stuff">
                            <li><a href="{{ path('index_article', {id: article.id}) }}">Read More<i class="icon-arrow-right22"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/front/commercial.html.twig
<div id="fh5co-started" class="fh5co-bg-dark">
    <div class="overlay"></div>
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>Hire Me!</h2>
                <p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet.</p>
                <p><a href="#" class="btn btn-default btn-lg">Contact Us</a></p>
            </div>
        </div>
    </div>
</div>

templates/front/contact.html.twig
<div id="fh5co-consult">
    <div class="video fh5co-video" style="background-image: url(images/contact.jpg);">
        <div class="overlay"></div>
    </div>
    <div class="choose animate-box">
        <h2>Contact</h2>
        {{ form_start(form, {'attr': {'novalidate': 'novalidate', 'action': path('index_contact') }}) }}

        <div class="row form-group">
                <div class="col-md-6">
                    {{ form_row(form.firstname) }}
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6">
                    {{ form_row(form.lastname) }}
                </div>
            </div>

            <div class="row form-group">
                <div class="col-md-12">
                    {{ form_row(form.email) }}
                </div>
            </div>

            <div class="row form-group">
                <div class="col-md-12">
                    {{ form_row(form.subject) }}
                </div>
            </div>

            <div class="row form-group">
                <div class="col-md-12">
                    {{ form_row(form.content) }}
                </div>
            </div>
            {% for message in app.flashes('success') %}
                <div class="alert alert-success" role="alert">
                    <strong> {{ message }}</strong>
                </div>
            {% endfor %}
            <div class="form-group">
                <input type="submit" value="Envoyer le mesage" class="btn btn-primary">
            </div>

        {{ form_end(form) }}
    </div>
</div>

templates/front/feature.html.twig
<div id="fh5co-features" class="animate-box">
    <div class="container">
        <div class="services-padding">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                    <h2>Mes services</h2>
                </div>
            </div>
            <div class="row">
                {% for service in services  %}
                    <div class="col-md-4 text-center">
                        <div class="feature-left">
                            <span class="icon">
                                <i class="{{ service.icon }}"></i>
                            </span>
                            <div class="feature-copy">
                                <h3>{{ service.name }}</h3>
                                <p>{{ service.description }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/front/footer.html.twig
<div id="fh5co-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>&copy; 2017 Free HTML5 Template. All Rights Reserved. <br>Designed by <a href="http://freehtml5.co" target="_blank">FreeHTML5.co</a> Demo Images: <a href="http://unsplash.com" target="_blank">Unsplash</a></p>
                <p>Credit Image : Photo by DXL on Unsplash</p>
                <p>Photo by Plush Design Studio on Unsplash</p>
            </div>
        </div>
    </div>
</div>

templates/front/header.html.twig
<header id="fh5co-header" class="fh5co-cover js-fullheight" role="banner" style="background-image:url(images/dxl-544035-unsplash.jpg);" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <div class="display-t js-fullheight">
                    <div class="display-tc js-fullheight animate-box" data-animate-effect="fadeIn">
                        <div class="profile-thumb" style="background: url(images/user.jpg);"></div>
                        <h1><span>{{ user.title }}</span></h1>
                        <h3><span>{{ user.name }}</span></h3>
                        <br>
                        <ul class="fh5co-social-icons">
                            {% if user.git is not empty %}
                                <li><a href="{{ user.git }}"><i class="icon-github"></i></a></li>
                            {% endif %}

                            {% if user.linkedin is not empty %}
                                <li><a href="{{ user.linkedin }}"><i class="icon-linkedin2"></i></a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/front/hire.html.twig
<div id="fh5co-started" class="fh5co-bg-dark">
    <div class="overlay"></div>
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>Contactez moi</h2>
                <p>{{ user.contact|nl2br }}</p>
                <p><a href="#fh5co-consult" class="btn btn-default btn-lg">Accéder au formulaire</a></p>
            </div>
        </div>
    </div>
</div>

templates/front/index.html.twig
{% extends 'base_fo.html.twig' %}

{% block body %}
    <div id="page">
        {{ render(controller(
            'App\\Controller\\IndexController::header'
        )) }}
        {{ render(controller(
            'App\\Controller\\IndexController::about'
        )) }}
        {{ render(controller(
            'App\\Controller\\IndexController::work'
        )) }}
        {{ render(controller(
            'App\\Controller\\IndexController::resume'
        )) }}
        {{ render(controller(
            'App\\Controller\\IndexController::service'
        )) }}
        {{ render(controller(
            'App\\Controller\\IndexController::blog'
        )) }}
        {{ render(controller(
            'App\\Controller\\IndexController::hire'
        )) }}
        {{ render(controller(
            'App\\Controller\\IndexController::contact'
        )) }}
    </div>
    {% include 'front/footer.html.twig' %}
{% endblock %}

templates/front/resume.html.twig
<div id="fh5co-resume" class="fh5co-bg-color">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>Mon CV</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-md-offset-0">
                <ul class="timeline">
                    <li class="timeline-heading text-center animate-box">
                        <div><h3>Expérience professionnelle</h3></div>
                    </li>
                    {% for job in jobs %}
                        {% if loop.index is not divisible by(2) %}
                            <li class="animate-box timeline-unverted">
                        {% else %}
                            <li class="timeline-inverted animate-box">
                        {% endif %}
                            <div class="timeline-badge"><i class="icon-suitcase"></i></div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h3 class="timeline-title">{{ job.title }}</h3>
                                    <span class="company">{{ job.undertitle }}</span>
                                </div>
                                <div class="timeline-body">
                                    {{ job.description|nl2br }}
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                    <br>
                    <li class="timeline-heading text-center animate-box">
                        <div><h3>Education</h3></div>
                    </li>
                    {% for school in schools %}
                        {% if loop.index is not divisible by(2) %}
                            <li class="animate-box timeline-unverted">
                        {% else %}
                            <li class="timeline-inverted animate-box">
                         {% endif %}
                        <div class="timeline-badge"><i class="icon-graduation-cap"></i></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h3 class="timeline-title">{{ school.title }}</h3>
                                <span class="company">{{ school.description }}</span>
                            </div>
                        </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/front/skill.html.twig
<div id="fh5co-skills" class="animate-box">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>Skills</h2>
            </div>
        </div>
        <div class="row row-pb-md">
            <div class="col-md-3 col-sm-6 col-xs-12 text-center">
                <div class="chart" data-percent="95"><span><strong>HTML5</strong>95%</span></div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 text-center">
                <div class="chart" data-percent="93"><span><strong>CSS3</strong>93%</span></div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 text-center">
                <div class="chart" data-percent="90"><span><strong>jQuery</strong>90%</span></div>
            </div>

            <div class="col-md-3 col-sm-6 col-xs-12 text-center">
                <div class="chart" data-percent="89"><span><strong>PHP</strong>89%</span></div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 text-center">
                <div class="chart" data-percent="85"><span><strong>MySQL</strong>85%</span></div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 text-center">
                <div class="chart" data-percent="90"><span><strong>AngularJS</strong>90%</span></div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 text-center">
                <div class="chart" data-percent="85"><span><strong>Ruby</strong>85%</span></div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 text-center">
                <div class="chart" data-percent="90"><span><strong>Java</strong>90%</span></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="progress-wrap">
                    <h3><span class="name-left">HTML5/CSS3</span><span class="value-right">95%</span></h3>
                    <div class="progress">
                        <div class="progress-bar progress-bar-1 progress-bar-striped active" role="progressbar"
                             aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width:90%">
                        </div>
                    </div>
                </div>
                <div class="progress-wrap">
                    <h3><span class="name-left">WordPress</span><span class="value-right">90%</span></h3>
                    <div class="progress">
                        <div class="progress-bar progress-bar-2 progress-bar-striped active" role="progressbar"
                             aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width:90%">
                        </div>
                    </div>
                </div>
                <div class="progress-wrap">
                    <h3><span class="name-left">PHP</span><span class="value-right">80%</span></h3>
                    <div class="progress">
                        <div class="progress-bar progress-bar-3 progress-bar-striped active" role="progressbar"
                             aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width:80%">
                        </div>
                    </div>
                </div>
                <div class="progress-wrap">
                    <h3><span class="name-left">Java</span><span class="value-right">85%</span></h3>
                    <div class="progress">
                        <div class="progress-bar progress-bar-4 progress-bar-striped active" role="progressbar"
                             aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width:85%">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="progress-wrap">
                    <h3><span class="name-left">Design</span><span class="value-right">100%</span></h3>
                    <div class="progress">
                        <div class="progress-bar progress-bar-5 progress-bar-striped active" role="progressbar"
                             aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
                        </div>
                    </div>
                </div>
                <div class="progress-wrap">
                    <h3><span class="name-left">Ruby</span><span class="value-right">70%</span></h3>
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped active" role="progressbar"
                             aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70%">
                        </div>
                    </div>
                </div>
                <div class="progress-wrap">
                    <h3><span class="name-left">Python</span><span class="value-right">85%</span></h3>
                    <div class="progress">
                        <div class="progress-bar progress-bar-1 progress-bar-striped active" role="progressbar"
                             aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width:85%">
                        </div>
                    </div>
                </div>
                <div class="progress-wrap">
                    <h3><span class="name-left">jQuery</span><span class="value-right">75%</span></h3>
                    <div class="progress">
                        <div class="progress-bar progress-bar-3 progress-bar-striped active" role="progressbar"
                             aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:75%">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/front/work.html.twig
<div id="fh5co-work" class="fh5co-bg-dark">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>Projets personnels</h2>
            </div>
        </div>
        <div class="row">
            {% for project in projects %}
                <div class="col-md-3 text-center col-padding animate-box">
                    <a href="{{ project.url }}" target="_blank" class="work" style="background-image: url({{ asset('uploads/project/' ~ project.picture) }});">
                        <div class="desc">
                            <h3>{{ project.name }}</h3>
                            <span>{{ project.description }}</span>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>